from twilio.rest import Client
import keys

def contact(name):
    client = Client(keys.account_sid, keys.auth_token)
    mes="Name:"+name+"""
Phone Number: 1234567890
Pincode: 600127

The above-listed individual is currently experiencing severe emotional distress and has expressed thoughts of self-harm or suicide in our recent chat conversation. We have taken immediate steps to reassure the user, provided information about local crisis hotlines, and encouraged them to seek professional help. However, due to the seriousness of the situation, we kindly request your immediate intervention to ensure their safety.

Your prompt attention to this matter is greatly appreciated.

This message was autogenerated by InnerVerse.
"""
    message = client.messages.create(
                                    body=mes,
                                    from_=keys.twilio_number,
                                    to=keys.target_number
                                )
    print("got called")
    #print(message.body)

  

# def contact(name) :
#     from twilio.rest import Client
#     account_sid = 'AC2572c9ce1544497f9dfd8064d12cba7b'
#     auth_token = 'ad281f0769aceec1c287b72672ff56bf'
#     client = Client(account_sid, auth_token)
#     message = client.messages.create(
#         from_='+19203357144',
#         body='this is my first message',
#         to='+919167282956'
#     )
#     print(message.sid)